version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0-stretch-node-browsers-legacy
    environment:
      CORS_ORIGIN: "*"
      APP_OUTPUT_FOLDER: ""
      APP_TEMPLATES_FOLDER: ""
      EXPO_ACCOUNT_USERNAME: ""
      EXPO_ACCOUNT_PASSWORD: ""
      EXPO_ORGANIZATION_ID: ""
    steps:
      - checkout
      - run : mvn test
      - store_artifacts:
          path:  target/site/jacoco
          destination: code_coverage
